name: publish
on: [push]
jobs:
publish-gin-qa-solutions-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ github.token }}
- name: Build the gin-qa-solutions Docker image
run: |
       docker build . --tag ghcr.io/pc085n/gin-qa-solutions:latest
       docker run ghcr.io/pc085n/gin-qa-solutions:latest
       docker push ghcr.io/pc085n/gin-qa-solutions:latest
